dataset: CIFAR100
first_split_size: 10
other_split_size: 10
schedule:
- 10
schedule_type: cosine
batch_size: 32
optimizer: Adam
lr: 0.001
momentum: 0.9
weight_decay: 0
model_type: zoo
model_name: clip_pt
#model_name: vit_pt_imnet
max_task: -1
dataroot: data
workers: 0
validation: False
train_aug: True
rand_split: True